# GitHub Sponsors
github: []

# Patreon
patreon:

# Open Collective
open_collective:

# Ko-fi
ko_fi:

# Tidelift
tidelift:

# Community Bridge
community_bridge:

# Liberapay
liberapay:

# IssueHunt
issuehunt:

# Otechie
otechie:

# LFX Crowdfunding
lfx_crowdfunding:

# Polar
polar:

# Buy Me a Coffee
buy_me_a_coffee:

# Thanks.dev
thanks_dev:

# PayPal
custom:
  - "https://www.paypal.com/paypalme/bungtempong99"
